# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: pquant-conda
channels:
  - bioconda
  - r
  - conda-forge
dependencies:
  - bioconda::bioconductor-msstats=4.0.0
  - bioconda::triqler
  - conda-forge::r-pheatmap
  - conda-forge::pandas
  - conda-forge::jupyterlab
  - bioconda::pyteomics
